### ISSUE TITLE
Packets for dnslib and requests?

### ISSUE THREAD

**Issue by JuniorJPDJ** [NucleaPeon/OpenWRT-Python3-Utils#3]
Pleeeaaasee?

**Comment by NucleaPeon** [comment]
I will look into packaging these. Thanks for the request, I'll post a response on my progress later.

**Comment by NucleaPeon** [comment]
Requests has been built and uploaded to this repo. I will begin work on dnslib

**Comment by NucleaPeon** [comment]
Uploaded dnslib into feed. I'm not familiar with dnslib, but it installs and can be imported.
Hopefully everything works the way you need it to. Cheers.
