### ISSUE TITLE
pycrypto not building

### ISSUE THREAD

**Issue by fundef1** [NucleaPeon/OpenWRT-Python3-Utils#4]
Pycrypto fails to build exactly as described in the readme, even after 
apt-get install gcc-4.8-multilib
apt-get install g++-4.8-multilib

but the egcs option is not available in menuconfig?
( I am using the SDK from lede-17.01: lede-sdk-ramips-mt7620_gcc-5.4.0_musl.Linux-x86_64

**Comment by NucleaPeon** [comment]
It won't build with the musl c library implementation. I had to use (e)glibc. It's mentioned at the bottom of the README.md.

**Comment by fundef1** [comment]
yes I read that in the readme,
but I couldn't figure out how to get the LEDE-SDK to build pycrypto using (e)glibc...
is there some magic incantation I can invoke?

**Comment by NucleaPeon** [comment]
Using the terminal, when I'm in the openwrt folder, I run ``make menuconfig``. Once there, I use the mouse arrows to move down to 

1.  **[*] Advanced configuration options  -->** 
2.  press enter
3.  move down to **[*] Toolchain Options --->** then there's the **C Library implementation (Use musl)** 
4. switch that so it reads **C Library implementation (Use (e)glibc)**

Press Escape until it prompts you to save your configuration and hit yes. Then run make or whatever process you use to build the project. 

This is what you are asking, right?

**Comment by NucleaPeon** [comment]
<img width="530" alt="musl" src="https://cloud.githubusercontent.com/assets/1475151/24633516/c5ef0a58-187d-11e7-9fea-459051003209.png">

**Comment by fundef1** [comment]
thanks for the support, but I don't have those options in the pre-built SDK, In the one I built myself I do have the advanced developer option but it's empty... but I guess the problem is with my setup then. Anyway thanks again for your help.

![image](https://cloud.githubusercontent.com/assets/12233640/24667681/9326b994-1964-11e7-8188-7a4eff6b2e45.png)

**Comment by fundef1** [comment]
Hi, I've asked this question on the LEDE forum and got exactly 0 replies.
I'm closing the issue here as I think the solution lies with LEDE rather than with your code here.

thanks for your assistance though!
